### ISSUE TITLE
Message key [FOUNDEO_CFML_COMPILER_ACCESS_KEY] doesn't exist

### ISSUE THREAD

**Issue by achilleus68** [foundeo/cfml-compiler#9]
Running this command from Powershell (administrator) from d:\web\local\bar\
`box cfcompile sourcePath=./foo destPath=./compiled cfengine=lucee@5.3.4`

an error occurs
(full trace at https://pastebin.com/TRgnDE86)

>  ✓ | Starting Server
>    | ✓ | Installing package [forgebox:lucee@5.3.4]
> 
> Starting RunWAR 3.8.1-SNAPSHOT
> Starting background cfml-compiler-server [lucee 5.3.4+80] from: /C:/Users/djiest/.CommandBox/lib/runwar-3.8.1-SNAPSHOT.jar
> Starting in background -
> 
> 
> Waiting for server to start: 0/60
> Starting compilation of: D:\web\local\bar\foo\
> Destination: D:\web\local\bar\compiled
> Stopping cfml-compiler-server...
> Stopped
> forgetting cfml-compiler-server...
> can't delete file C:\Users\djiest\.CommandBox\server\278BFB277242452B666AF60F42DF8B2C-cfml-compiler-server\lucee-5.3.4.80\logs\server.out.txt
> Did you leave the server running?
> cfml-compiler-server not deleted.
> ERROR (4.7.0+00026)
> 
> Response had status: 500 Internal Server Error
> 
> 
> 
> 
> Lucee 5.3.4.80 Error (expression)
> 
> Message key [FOUNDEO_CFML_COMPILER_ACCESS_KEY] doesn't exist
> 
> Stacktrace The Error Occurred in
> D:\web\local\bar\foo\__cfml-compiler\compiler.cfc: line 60
> 
>     58:                 var sysAccessKey = createObject("java", "java.lang.System").getProperty("cfmlcompilerkey");
>     59:                 var result = {errors:[]};
>     60:                 if (arguments.accessKey != server.system.environment.foundeo_cfml_compiler_access_key) {
>     61:                         return {path:"*", message:"Access Denied"};
>     62:                 }
>     
>     
>     
> 
> Java Stacktrace lucee.runtime.exp.ExpressionException: key [FOUNDEO_CFML_COMPILER_ACCESS_KEY] doesn't exist
>         at lucee.runtime.type.util.StructSupport.invalidKey(StructSupport.java:67)
>

**Comment by pfreitag** [comment]
@djiest it might be due to the version of commandbox you are using - it looks like you are using 4.7.0 is that correct?

The command sets an environment variable foundeo_cfml_compiler_access_key before it starts the compiler server with a random token in it. This is just to ensure that only the command can invoke the server. It is using `systemSettings.setSystemSetting` in commandbox to do this, so maybe in earlier versions of CommandBox it doesn't set the environment variable. I'll have to look into that.

I would guess using the latest version of commandbox will fix it.

**Comment by achilleus68** [comment]
@pfreitag you are correct. I updated my box, and now it's running, thanks
